# -*- coding: utf-8 -*-
"""Propulsão_Grupo2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14h-Pi_X3VM4ETATw0FP3FyZihRYamW9Z

# TRABALHO DE SISTEMAS PROPULSIVOS - GRUPO 2

Este código simula o funcionamento de 4 tipos de motores aeronáuticos: turbojato, turbofan, ramjet e turbo-hélice, em ponto de projeto e fora dele ("off-design").

O primeiro bloco de código contém diversos dicionários com os dados de projeto de cada motor. Para simular um outro motor, copie um desses dicionários e substitua os valores, sem deletar nenhum campo. Siga o formato do respectivo tipo (os primeiros dicionários são de turbofan/turbojato/ramjet e depois são os de turbo-hélice).

O segundo bloco possui as funções do turbofan, do turbojato e do ramjet. As duas últimas utilizam as funções do primeiro. O terceiro bloco possui a função do turbo-hélice.

O quarto bloco é onde o motor a ser simulado é escolhido (procure pela variável dados_atuais e substitua o que está depois do igual pelo nome do seu dicionário, sem deletar o .copy() que segue).

Depois, basta executar tudo. Será pedido o tipo de motor a ser simulado (1 - turbojato, 2 - turbofan, 3 - ramjet, 4 - turbo-hélice), e se deseja ou não rodar fora do ponto de operação. Se sim, deverá informar a rotação N2 (de 0 a 1).

Caso deseja criar gráficos em certas análises, faça-o em um novo bloco de código, depois dos blocos já aqui presentes.
"""

# TRABALHO DE SISTEMAS PROPULSIVOS
# Grupo 2

# Imports
import numpy as np

# BLOCO 1 - DADOS DE ENTRADA

# Cada motor tem um dicionário específico com seus respectivos dados.
# A escolha do motor para simulação é feita no início do bloco 3, procurar dados_atuais
# Para usar um outro motor, copie um desses dicionários e substitua os valores. Não delete nenhum campo.

# ==== DICIONÁRIOS DE TURBOFAN/TURBOJATO/RAMJET ========

# Motor no enunciado do roteiro
dados_motor_enunc = {
    # Condições de Voo
    "M": 0.0,              # Mach de voo
    "Pa": 101.63,          # Pressão atmosférica (kPa)
    "Ta": 290.0,           # Temperatura atmosférica (K)
    "m_ar_padrao": 756,    # Vazão total de ar a 288,15 K e 101,3 kPa (kg/s)

    # Eficiências de componentes
    "eta_inlet": 0.97,
    "eta_fan": 0.93,
    "eta_compressor": 0.90,
    "eta_combust": 0.9995,
    "eta_turb_comp": 0.95,
    "eta_turb_livre": 0.932,
    "eta_bocal_hot": 0.98,
    "eta_bocal_fan": 0.98,

    # Dados termodinâmicos
    "PCI": 45000,
    "R_medio": 288.3,
    "gama_atm": 1.4,
    "Cp_combust": 1.11,
    "gama_inlet": 1.4,
    "gama_fan": 1.4,
    "gama_compressor": 1.37,
    "gama_combust": 1.35,
    "gama_turb_comp": 1.33,
    "gama_turb_livre": 1.33,
    "gama_bocal_hot": 1.36,
    "gama_bocal_fan": 1.4,
    "T04": 1550,                    # Temperatura de saída da câmara de combustão
    "Prc": 17.2,                    # Razão de pressão no compressor
    "Prf": 1.69,                    # Razão de pressão no fan
    "B": 4.749,                     # Razão de passagem (bypass)
    "perda_camara": 0,              # Perda de pressão na câmara de combustão
    "pos_queimador_ligado": False,  # True para ligado, False para desligado
    "dT_pq": 600.0,                 # Temperatura de saída do pós-queimador [K], valor aqui é um exemplo
    "eta_combust_pq": 0.95,         # Eficiência da combustão no pós-queimador

}

# Motor do exemplo 2.1 - para validação
dados_ex21 = {

    # OS DADOS RELATIVOS AO TURBOFAN FORAM MANTIDOS IGUAIS AO DO ENUNCIADO DO TRABALHO PRA VER SE O CÓDIGO DO TURBOJATO FUNCIONA CERTO

    # Condições de Voo
    "M": 0.85,              # Mach de voo
    "Pa": 18.75,            # Pressão atmosférica (kPa)
    "Ta": 216.7,            # Temperatura atmosférica (K)
    "m_ar_padrao": 756,     # Vazão total de ar a 288,15 K e 101,3 kPa (kg/s)

    # Eficiências de componentes
    "eta_inlet": 0.97,
    "eta_fan": 0.93,
    "eta_compressor": 0.85,
    "eta_combust": 1,
    "eta_turb_comp": 0.90,
    "eta_turb_livre": 0.932,
    "eta_bocal_hot": 0.98,
    "eta_bocal_fan": 0.98,

    # Dados termodinâmicos
    "PCI": 45000,
    "R_medio": 288.3,
    "gama_atm": 1.4,
    "Cp_combust": 1.11,
    "gama_inlet": 1.4,
    "gama_fan": 1.4,
    "gama_compressor": 1.37,
    "gama_combust": 1.35,
    "gama_turb_comp": 1.33,
    "gama_turb_livre": 1.33,
    "gama_bocal_hot": 1.36,
    "gama_bocal_fan": 1.4,
    "T04": 1600,                    # Temperatura de saída da câmara de combustão
    "Prc": 30,                      # Razão de pressão no compressor
    "Prf": 1.69,                    # Razão de pressão no fan
    "B": 4.749,                     # Razão de passagem (bypass)
    "perda_camara": 0,              # Perda de pressão na câmara de combustão
    "pos_queimador_ligado": False,   # True para ligado, False para desligado
    "dT_pq": 600.0,                 # Temperatura de saída do pós-queimador [K]
    "eta_combust_pq": 0.95,         # Eficiência da combustão no pós-queimador

}

# Motor do exemplo 2.2 - para validação
dados_ex22 = {

    # Condições de Voo
    "M": 0.85,              # Mach de voo
    "Pa": 18.75,            # Pressão atmosférica (kPa)
    "Ta": 216.7,            # Temperatura atmosférica (K)
    "m_ar_padrao": 756,     # Vazão total de ar a 288,15 K e 101,3 kPa (kg/s)

    # Eficiências de componentes
    "eta_inlet": 0.97,
    "eta_fan": 0.85,
    "eta_compressor": 0.85,
    "eta_combust": 1,
    "eta_turb_comp": 0.90,
    "eta_turb_livre": 0.9,
    "eta_bocal_hot": 0.98,
    "eta_bocal_fan": 0.98,

    # Dados termodinâmicos
    "PCI": 45000,
    "R_medio": 288.3,
    "gama_atm": 1.4,
    "Cp_combust": 1.11,
    "gama_inlet": 1.4,
    "gama_fan": 1.4,
    "gama_compressor": 1.37,
    "gama_combust": 1.35,
    "gama_turb_comp": 1.33,
    "gama_turb_livre": 1.33,
    "gama_bocal_hot": 1.36,
    "gama_bocal_fan": 1.4,
    "T04": 1600,                    # Temperatura de saída da câmara de combustão
    "Prc": 20,                      # Razão de pressão no compressor
    "Prf": 1.5,                     # Razão de pressão no fan
    "B": 5,                         # Razão de passagem (bypass)
    "perda_camara": 0,              # Perda de pressão na câmara de combustão
    "pos_queimador_ligado": False,   # True para ligado, False para desligado
    "dT_pq": 600.0,                 # Temperatura de saída do pós-queimador [K]
    "eta_combust_pq": 0.95,         # Eficiência da combustão no pós-queimador

}

# Motor do exemplo 2.3 - para validação
dados_ex23 = {

    # Condições de Voo
    "M": 0.0,              # Mach de voo
    "Pa": 101.63,          # Pressão atmosférica (kPa)
    "Ta": 290,             # Temperatura atmosférica (K)
    "m_ar_padrao": 756,    # Vazão total de ar a 288,15 K e 101,3 kPa (kg/s)

    # Eficiências de componentes
    "eta_inlet": 0.97,
    "eta_fan": 0.93,
    "eta_compressor": 0.90,
    "eta_combust": 0.9995,
    "eta_turb_comp": 0.95,
    "eta_turb_livre": 0.932,
    "eta_bocal_hot": 0.98,
    "eta_bocal_fan": 0.98,

    # Dados termodinâmicos
    "PCI": 45000,
    "R_medio": 288.3,
    "gama_atm": 1.4,
    "Cp_combust": 1.11,
    "gama_inlet": 1.4,
    "gama_fan": 1.4,
    "gama_compressor": 1.37,
    "gama_combust": 1.35,
    "gama_turb_comp": 1.33,
    "gama_turb_livre": 1.33,
    "gama_bocal_hot": 1.36,
    "gama_bocal_fan": 1.4,
    "T04": 1550,                      # Temperatura de saída da câmara de combustão
    "Prc": 17.2,                      # Razão de pressão no compressor
    "Prf": 1.69,                      # Razão de pressão no fan
    "B": 4.749,                       # Razão de passagem (bypass)
    "perda_camara": 0.05,             # Perda de pressão na câmara de combustão
    "pos_queimador_ligado": False,    # True para ligado, False para desligado
    "dT_pq": 600.0,                   # Temperatura de saída do pós-queimador [K]
    "eta_combust_pq": 0.95,           # Eficiência da combustão no pós-queimador


}

# EXERCICIO 7.1

dados_ex71 = {
    "M": 0.0,
    "Pa": 101.3,
    "Ta": 288.15,
    "m_ar_padrao": 8.49,

    "eta_inlet": 0.85,
    "eta_compressor": 0.75,
    "eta_combust": 1.0,
    "eta_turb_comp": 0.90,
    "eta_turb_livre": 0.90,
    "eta_bocal_hot": 0.98,

    "PCI": 45000,
    "R_medio": 288.3,
    "Cp_combust": 1.11,
    "Cp_compressor": 1.004,

    "gama_atm": 1.4,
    "gama_inlet": 1.4,
    "gama_compressor": 1.37,
    "gama_turb_comp": 1.33,
    "gama_turb_livre": 1.33,
    "gama_bocal_hot": 1.33,

    "T04": 1600.0,
    "Prc": 15.77,
    "perda_camara": 0.0,

    "Prtl": 2.87,
    "eta_gearbox": 0.98,
    "eta_prop": 0.85,
    "Cp_turb_livre": 1.16,
}


# ==== DICIONÁRIOS DE TURBO-HÉLICE ========

# EXERCÍCIO 7.2

dados_ex72 = {
    "M": 0.45,
    "Pa": 41.0,
    "Ta": 246.55,
    "m_ar_padrao": 8.49,

    "eta_inlet": 0.85,
    "eta_compressor": 0.75,
    "eta_combust": 1.0,
    "eta_turb_comp": 0.90,
    "eta_turb_livre": 0.90,
    "eta_bocal_hot": 0.98,

    "PCI": 45000,
    "R_medio": 288.3,
    "Cp_combust": 1.11,
    "Cp_compressor": 1.004,

    "gama_atm": 1.4,
    "gama_inlet": 1.4,
    "gama_compressor": 1.37,
    "gama_turb_comp": 1.33,
    "gama_turb_livre": 1.33,
    "gama_bocal_hot": 1.33,

    "T04": 1600.0,
    "Prc": 15.77,
    "perda_camara": 0.0,

    "Prtl": 2.87,
    "eta_gearbox": 0.98,
    "eta_prop": 0.85,
    "Cp_turb_livre": 1.16,
}

# Dados para o turbo hélice
dados_turbhelice = {
    "Prtl": 2.87,             # razão de expansão da turbina livre (Valor ajustado para se atingir a potência termodinâmica que o fabricante informou.)
    "eta_gearbox": 0.98,      # eficiência da caixa redutora
    "eta_prop": 0.95,         # eficiência da hélice
    "Cp_turb_livre": 1.16,    # kJ/(kg.K)

}

print("Dados carregados com sucesso")

# BLOCO 2 - FÓRMULAS E FUNÇÕES TURBOFAN/TURBOJATO/RAMJET

# =================================================================
# TURBOFAN
# =================================================================

def simular_turbofan(dados, fora_de_projeto=False, N2=1.0, tipo_motor='turbofan'):

    # =================================================================
    # VARIÁVEIS LOCAIS (que podem sofrer modificação se sair do ponto de projeto)
    # =================================================================
    B = dados["B"]
    Prf = dados["Prf"]
    Prc = dados["Prc"]
    T04 = dados["T04"]
    eta_fan = dados["eta_fan"]
    eta_compressor = dados["eta_compressor"]
    eta_combust = dados["eta_combust"]
    eta_turb_comp = dados["eta_turb_comp"]
    eta_turb_livre = dados["eta_turb_livre"]

    # Vazão mássica de ar base
    m_ar = dados["m_ar_padrao"] * (288.15 / 101.30) * (dados["Pa"] / dados["Ta"])

    # N1 padrão (será sobrescrito se for fora de projeto)
    N1 = N2

    # =================================================================
    # CORREÇÕES PARA FORA DE PROJETO
    # =================================================================
    if fora_de_projeto and N2 != 1.0:
        # Rotação N1 em função de N2
        N1 = 1.4166 * N2 - 0.40478

        # Correções do Fan
        perc_B = -0.83241 * (N1**2) + 0.38824 * N1 + 1.4263
        B = dados["B"] * perc_B

        A_prf = -0.00179 * (dados["B"]**2) + 0.00687 * dados["B"] + 0.5
        C_prf = 0.011 * dados["B"] + 0.53782
        perc_Prf = A_prf * (N1**2) - 0.043317 * N1 + C_prf
        Prf = dados["Prf"] * perc_Prf

        perc_eta_f = -6.6663 * (N1**4) + 17.752 * (N1**3) - 17.469 * (N1**2) + 7.7181 * N1 - 0.32985
        eta_fan = dados["eta_fan"] * perc_eta_f

        # Correções do Compressor (usam N2)
        perc_Prc = -6.0730 * (N2**3) + 14.821 * (N2**2) - 10.042 * N2 + 2.2915
        Prc = dados["Prc"] * perc_Prc

        perc_eta_c = -1.1234 * (N2**2) + 2.1097 * N2 + 0.018617
        eta_compressor = dados["eta_compressor"] * perc_eta_c

        # Correções da Câmara (usam N2)
        perc_T04 = 0.81821 * (N2**2) - 0.22401 * N2 + 0.41842
        T04 = dados["T04"] * perc_T04

        perc_eta_b = 1.1630 * (N2**3) - 3.0851 * (N2**2) + 2.7312 * N2 + 0.1913
        eta_combust = dados["eta_combust"] * perc_eta_b

        # Correções das Turbinas
        perc_eta_t = -0.06749 * (N2**2) + 0.2564 * N2 + 0.81153
        eta_turb_comp = dados["eta_turb_comp"] * perc_eta_t

        perc_eta_tf = -0.06749 * (N1**2) + 0.2564 * N1 + 0.81153
        eta_turb_livre = dados["eta_turb_livre"] * perc_eta_tf

        # Correção da Vazão (usa N2)
        perc_m_ar = -6.6970 * (N2**3) + 17.001 * (N2**2) - 12.170 * N2 + 2.8717
        m_ar = m_ar * perc_m_ar

    # =================================================================
    # TRAVAS DE SEGURANÇA PARA TURBOJATO E RAMJET
    # Redefine os valores de B, Prf e Prc após serem corrigidos (sem necessidade)
    # =================================================================

    if dados["B"] == 0.0:
        B = 0.0
        Prf = 1.0

    if dados["Prc"] == 1.0:
        Prc = 1.0
        eta_turb_comp = dados["eta_turb_comp"]
        eta_combust = dados["eta_combust"]


    # =================================================================
    # EQUAÇÕES
    # =================================================================

    # Entrada de Ar
    T02 = dados["Ta"] * (1 + ((dados["gama_inlet"] - 1) / 2) * (dados["M"] ** 2)) # Eq 18
    P02 = dados["Pa"] * (1 + dados["eta_inlet"] * (T02 / dados["Ta"] - 1)) ** (dados["gama_inlet"] / (dados["gama_inlet"] - 1)) # Eq 19

    # Fan
    P08 = P02 * Prf # Eq 22
    T08 = T02 * (1 + (1 / eta_fan) * ((Prf ** ((dados["gama_fan"] - 1) / dados["gama_fan"])) - 1)) # Eq 23
    u_sf = np.sqrt(2 * dados["eta_bocal_fan"] * (dados["gama_bocal_fan"] / (dados["gama_bocal_fan"] - 1)) * dados["R_medio"] * T08 * (1 - (dados["Pa"] / P08) ** ((dados["gama_bocal_fan"] - 1) / dados["gama_bocal_fan"]))) # Eq 29

    # Compressor
    P03 = P08 * Prc # Eq 20
    T03 = T08 * (1 + (1 / eta_compressor) * ((Prc ** ((dados["gama_compressor"] - 1) / dados["gama_compressor"]) - 1))) # Eq 21

    # Câmara de Combustão
    P04 = P03 * (1 - dados["perda_camara"]) # Perda de pressão na câmara de combustão

    # A T04 dada no enunciado é a ideal, mas ela muda quando há queda de pressão
    # Se não houver, a equação abaixo dá certo também
    gama_cam = dados["gama_combust"]
    T04_efetiva = T04 * (P04 / P03) ** ((gama_cam - 1) / gama_cam)
    f_camara = ((T04_efetiva / T03) - 1) / (((eta_combust * dados["PCI"]) / (dados["Cp_combust"] * T03)) - (T04_efetiva / T03)) # Razão Combustível/Ar, Eq 24

    # Turbina do Compressor
    TET = T04_efetiva - (T03 - T08) # Eq 25 (1)
    PET = P04 * (1 - (1 / eta_turb_comp) * (1 - (TET / T04_efetiva))) ** (dados["gama_turb_comp"] / (dados["gama_turb_comp"] - 1)) # Eq 26 (1)

    # Turbina do Fan
    T05 = TET - (B + 1) * (T08 - T02) # Eq 25 (2)
    P05 = PET * (1 - (1 / eta_turb_livre) * (1 - (T05 / TET))) ** (dados["gama_turb_livre"] / (dados["gama_turb_livre"] - 1)) # Eq 26 (2)

    # Pós-Queimador (afterburner)
    pq_ligado = dados.get("pos_queimador_ligado", False)

    if pq_ligado:
        dT_pq = dados.get("dT_pq", 0.0)
        eta_pq = dados.get("eta_combust_pq", 0.95)

        # Temperatura após PQ
        T06 = T05 + dT_pq
        razao_temp_pq = T06/T05

        # Sem perda de pressão
        P06 = P05

        # Razão combustível/ar extra injetada no pós-queimador
        f_pq = (razao_temp_pq - 1)/(((eta_pq * dados["PCI"])/(dados["Cp_combust"] * T05))-(razao_temp_pq))


    else:
        T06 = T05
        P06 = P05
        f_pq = 0.0

    # Bocal de Gases Quentes - velocidade de saída
    # Condição adicionada para evitar erro caso a rotação N2
    # escolhida fora do ponto de projeto não seja suficiente para aspirar o ar
    if P06 > dados["Pa"]:
      u_s = np.sqrt(2 * dados["eta_bocal_hot"] * (dados["gama_bocal_hot"] / (dados["gama_bocal_hot"] - 1)) * dados["R_medio"] * T06 * (1 - (dados["Pa"] / P06) ** ((dados["gama_bocal_hot"] - 1) / dados["gama_bocal_hot"]))) # Eq 28
    else:
      u_s = 0.0


    # =================================================================
    # CÁLCULO DOS RESULTADOS FINAIS
    # =================================================================

    # Velocidade de Voo (u) - u = M * sqrt(gamma * R * Ta)
    u = dados["M"] * np.sqrt(dados["gama_atm"] * dados["R_medio"] * dados["Ta"])

    # Vazões Mássicas
    m_ar_H = m_ar / (1 + B)   # ar quente - o roteiro fala pra usar o B não corrigido pela rotação, mas aí a soma não bate então usei o corrigido
    m_ar_C = B * m_ar_H       # ar frio - usando o B corrigido pela rotação

    m_f_camara = f_camara * m_ar_H  # Vazão de combustível na câmara
    m_f_pq = f_pq * m_ar_H          # Vazão de combustível do pós-queimador
    m_f = m_f_camara + m_f_pq       # Vazão total de combustível (Câmara + PQ)

    # Razão combustível/ar total
    f = f_camara + f_pq

    # Empuxo Específico = T/m_ar_H
    empuxo_especifico = ((1 + f) * u_s - u) + B * (u_sf - u)

    # Empuxo Total (kN)
    empuxo_total = m_ar_H * empuxo_especifico / 1000.0

    # TSFC recalculado com base na massa de combustível total e empuxo total gerado
    if empuxo_total > 0:
        # TSFC = (m_f [kg/s] / empuxo_total [kN]) * 1000
        TSFC = (m_f / empuxo_total)
        fuel_total = m_f * 3600.0  # Consumo total em kg/h
    else:
        TSFC = float('inf')
        fuel_total = 0.0

    # =================================================================
    # EXIBIÇÃO DOS RESULTADOS
    # =================================================================

    # Sufixo dinâmico - para o print dos valores corrigidos
    sufixo = " (corrigida)" if (fora_de_projeto and N2 != 1.0) else ""

    # Respostas - separadas em dicionários para exibição condicional
    # Seção 1: Parâmetros Operacionais (Se for Turbojato/Ramjet, esconde dados do Fan)
    param_operacionais = {
        "Mach de Voo (M)": dados["M"],
        "Velocidade de Voo (u) [m/s]": u,

    }
    if tipo_motor != 'ramjet':
        param_operacionais["Rotação N2 (Compressor)"] = N2
    if tipo_motor == 'turbofan':
        param_operacionais["Rotação N1 (Fan)"] = N1
        param_operacionais[f"Razão de Passagem (B){sufixo}"] = B
        param_operacionais[f"Razão de Pressão do Fan (Prf){sufixo}"] = Prf
        param_operacionais[f"Eficiência do Fan{sufixo}"] = eta_fan

    param_operacionais[f"Razão de Pressão do Comp. (Prc){sufixo}"] = Prc
    if tipo_motor != 'ramjet':
        param_operacionais[f"Eficiência do Compressor{sufixo}"] = eta_compressor
    param_operacionais[f"Temp. total da Câmara (T04) [K]{sufixo}"] = T04

    # Seção 2: Vazões Mássicas
    if fora_de_projeto and N2 != 1.0:
        rotulo_mar = "Vazão de ar corrigida para altitude e off-design (m_ar) [kg/s]"
    else:
        rotulo_mar = "Vazão de ar corrigida para a altitude (m_ar) [kg/s]"

    vazoes = {
        rotulo_mar: m_ar,
        "Vazão de ar quente (m_aH) [kg/s]": m_ar_H,
    }
    if tipo_motor == 'turbofan':
        vazoes["Vazão de ar frio (m_aC) [kg/s]"] = m_ar_C

    vazoes["Vazão de combustível da câmara (m_f_camara) [kg/s]"] = m_f_camara
    if pq_ligado:
        vazoes["Vazão de combustível do pós-queimador (m_f_pq) [kg/s]"] = m_f_pq
    vazoes["Vazão de combustível total (m_f) [kg/s]"] = m_f

    # Seção 3: Entrada de Ar e Fan
    entrada_e_fan = {
        "Temp. total no final da entrada de ar (T02) [K]": T02,
        "Pressão total no final da entrada de ar (P02) [kPa]": P02,
    }
    if tipo_motor == 'turbofan':
        entrada_e_fan["Temp. total na saída do fan (T08) [K]"] = T08
        entrada_e_fan["Pressão total na saída do fan (P08) [kPa]"] = P08
        entrada_e_fan["Velocidade de saída do ar frio (fan) (u_sf) [m/s]"] = u_sf

    # Seção 4: Compressor e Câmara
    compressor_e_camara = {}
    if tipo_motor != 'ramjet':
        compressor_e_camara["Temp. total na saída do compressor (T03) [K]"] = T03
        compressor_e_camara["Pressão total na saída do compressor (P03) [kPa]"] = P03
    else:
        compressor_e_camara["Temp. total na saída do pós-difusor (T03) [K]"] = T03
        compressor_e_camara["Pressão total na saída do pós-difusor (P03) [kPa]"] = P03
    compressor_e_camara["Temp. total na saída da câmara (T04) [K]"] = T04_efetiva
    compressor_e_camara["Pressão total na saída da câmara (P04) [K]"] = P04
    compressor_e_camara["Razão combustível/ar da câmara (f_camara)"] = f_camara

    # Seção 5: Turbinas
    turbinas = {}
    if tipo_motor == 'turbojato':
        # No Turbojato, a saída da única turbina já é a entrada do bocal/PQ (Estágio 5)
        turbinas["Temp. total na saída da turbina (T05) [K]"] = TET
        turbinas["Pressão total na saída da turbina (P05) [kPa]"] = PET

    elif tipo_motor == 'turbofan':
        # No Turbofan, tem o estágio intermediário (entre turbinas) e o estágio final (5)
        turbinas["Temp. total pós-turbina do comp. (TET) [K]"] = TET
        turbinas["Pressão total pós-turbina do comp. (PET) [kPa]"] = PET
        turbinas["Temp. total na saída da turbina do fan (T05) [K]"] = T05
        turbinas["Pressão total na saída da turbina do fan (P05) [kPa]"] = P05

    # Seção 6: Pós-Queimador
    pos_queimador = {}
    if pq_ligado:
        pos_queimador["Delta de Temp. aplicado (dT_pq) [K]"] = dados.get("dT_pq", 0.0)
        pos_queimador["Razão de Temperatura do PQ (T06/T05)"] = razao_temp_pq
        pos_queimador["Razão combustível/ar no PQ (f_pq)"] = f_pq

    # Seção 7: Bocal de Gases Quentes
    bocal_quente = {
        "Temp. total na entrada do bocal (T06) [K]": T06,
        "Pressão total na entrada do bocal (P06) [kPa]": P06,
        "Velocidade de saída dos gases (u_s) [m/s]": u_s,
    }

    # Criando o Dicionário Final ordenado
    respostas = {
        "PARÂMETROS OPERACIONAIS": param_operacionais,
        "VAZÕES MÁSSICAS": vazoes,
        "ENTRADA DE AR": entrada_e_fan,
        "COMPRESSOR E CÂMARA": compressor_e_camara,
    }

    # Adiciona as turbinas se não for Ramjet (Ramjet não tem turbinas)
    if tipo_motor != 'ramjet':
        respostas["TURBINAS"] = turbinas

    # Se o pós-queimador estiver ligado, injeta a seção dele
    if pq_ligado:
        respostas["PÓS-QUEIMADOR"] = pos_queimador

    # Injeta a seção dedicada do bocal
    respostas["BOCAL DE GASES QUENTES"] = bocal_quente

    # Seção Final: Desempenho Global
    respostas["DESEMPENHO GLOBAL"] = {
        "Empuxo Específico [m/s]": empuxo_especifico,
        "Empuxo Total [kN]": empuxo_total,
        "Consumo Específico (TSFC) [kg/(kN.s)]": TSFC,
        "Consumo total de combustível [kg/h]": fuel_total,
    }

    # Se for Turbofan, altera o nome mantendo a posição física correta
    if tipo_motor == 'turbofan':
        # Ordenar
        respostas = { ("ENTRADA DE AR E FAN" if k == "ENTRADA DE AR" else k): v for k, v in respostas.items() }

    return respostas


# =================================================================
# TURBOJATO
# =================================================================

# O turbojato é um turbofan com B = 0 e Prf = 1
def simular_turbojato(dados, fora_de_projeto=False, N2=1.0):
    dados_tj = dados.copy()
    dados_tj["Prf"] = 1.0
    dados_tj["B"] = 0.0
    return simular_turbofan(dados_tj, fora_de_projeto, N2, tipo_motor='turbojato')

# =================================================================
# RAMJET
# =================================================================

# O ramjet é um turbojato sem compressor - B = 0, Prf = 1, Prc = 1
def simular_ramjet(dados, fora_de_projeto=False, N2=1.0):
    dados_ram = dados.copy()
    dados_ram["B"] = 0.0
    dados_ram["Prf"] = 1.0
    dados_ram["Prc"] = 1.0
    return simular_turbofan(dados_ram, fora_de_projeto, N2, tipo_motor='ramjet')

print("Funções carregadas com sucesso")

# =================================================================
# Bloco 4 - Equações TURBO-HÉLICE
# =================================================================

def simular_turbohelice(dados, fora_de_projeto=False, N2=1.0):
    Prc = dados["Prc"]
    Prtl = dados["Prtl"]
    T04 = dados["T04"]

    eta_compressor = dados["eta_compressor"]
    eta_turb_comp = dados["eta_turb_comp"]
    eta_turb_livre = dados["eta_turb_livre"]

    if fora_de_projeto:
        corr_Prc = -6.0730*N2**3 + 14.821*N2**2 - 10.042*N2 + 2.2915
        corr_T04 = 0.81821*N2**2 - 0.22401*N2 + 0.41842
        corr_eta_c = -1.1234*N2**2 + 2.1097*N2 + 0.018617
        corr_turb_comp = -0.06749*N2**2 + 0.25640*N2 + 0.81153
        corr_m_ar = -6.6970*N2**3 + 17.001*N2**2 - 12.170*N2 + 2.8717
        corr_eta_turb_livre = 19.062*N2**3 - 52.456*N2**2 + 47.887*N2 - 13.489
        corr_Prtl = -18.063*N2**3 + 42.469*N2**2 - 31.480*N2 + 8.0681

        Prc *= corr_Prc
        Prtl *= corr_Prtl
        T04 *= corr_T04
        eta_compressor *= corr_eta_c
        eta_turb_comp *= corr_turb_comp
        eta_turb_livre *= corr_eta_turb_livre

        m_ar = (
            dados["m_ar_padrao"]
            * (dados["Pa"] / dados["Ta"])
            / (101.3 / 288.15)
            * corr_m_ar
        )
    else:
        m_ar = dados["m_ar_padrao"] * (dados["Pa"] / dados["Ta"]) / (101.3 / 288.15)

    # ENTRADA DE AR
    T02 = dados["Ta"] * (1 + ((dados["gama_inlet"] - 1) / 2) * dados["M"]**2)

    P02 = dados["Pa"] * (
        1 + dados["eta_inlet"] * (T02 / dados["Ta"] - 1)
    ) ** (dados["gama_inlet"] / (dados["gama_inlet"] - 1))

    # COMPRESSOR
    P03 = P02 * Prc

    T03 = T02 * (
        1
        + (Prc ** ((dados["gama_compressor"] - 1) / dados["gama_compressor"]) - 1)
        / eta_compressor
    )

    # CÂMARA DE COMBUSTÃO
    P04 = P03 * (1 - dados["perda_camara"])

    f = (
        dados["Cp_combust"] * (T04 - T03)
    ) / (
        dados["eta_combust"] * dados["PCI"]
        - dados["Cp_combust"] * T04
    )

    m_f = f * m_ar
    m_total = m_ar * (1 + f)

    # TURBINA DO COMPRESSOR
    # Modelo usado no Exemplo 7.1 do livro
    T05 = T04 - (T03 - T02)

    T05s = T04 - (T04 - T05) / eta_turb_comp

    P05 = P04 * (T05s / T04) ** (
        dados["gama_turb_comp"] / (dados["gama_turb_comp"] - 1)
    )

    # TURBINA LIVRE
    P06 = P05 / Prtl

    T06s = T05 * (P06 / P05) ** (
        (dados["gama_turb_livre"] - 1) / dados["gama_turb_livre"]
    )

    W_tl_s = dados["Cp_turb_livre"] * (T05 - T06s)
    W_tl = eta_turb_livre * W_tl_s

    # Para reproduzir a planilha do livro, ela usa vazão arredondada 8,7 kg/s
    m_total_potencia = dados.get("m_turbina_potencia", round(m_total, 1))

    POT_tl = W_tl * m_total_potencia
    T06 = T05 - W_tl / dados["Cp_turb_livre"]

    # BOCAL
    if P06 > dados["Pa"]:
        Cp_bocal = dados.get("Cp_bocal_hot", 1.15916) * 1000

        T7s = T06 * (dados["Pa"] / P06) ** (
            (dados["gama_bocal_hot"] - 1) / dados["gama_bocal_hot"]
        )

        u_s = np.sqrt(
            2 * dados["eta_bocal_hot"] * Cp_bocal * (T06 - T7s)
        )
    else:
        T7s = T06
        u_s = 0.0

    # HÉLICE / CAIXA
    POT_eixo = dados["eta_gearbox"] * POT_tl
    POT_util = dados["eta_prop"] * POT_eixo

    u = dados["M"] * np.sqrt(
        dados["gama_atm"] * dados["R_medio"] * dados["Ta"]
    )

    if abs(u) > 1e-9:
        empuxo_helice_kN = (POT_util * 1000 / u) / 1000
    else:
        empuxo_helice_kN = np.nan

    # EMPUXO DO BOCAL
    empuxo_especifico_bocal_ms = (1 + f) * u_s - u
    empuxo_especifico_bocal_kNs_kg = empuxo_especifico_bocal_ms / 1000
    empuxo_bocal_kN = m_ar * empuxo_especifico_bocal_ms / 1000

    if np.isfinite(empuxo_helice_kN):
        empuxo_total_kN = empuxo_bocal_kN + empuxo_helice_kN
    else:
        empuxo_total_kN = np.nan

    # CONSUMO
    BSFC = m_f / POT_tl if POT_tl > 0 else np.nan
    EBSFC = BSFC if abs(u) <= 1e-9 else np.nan
    TSFC = m_f / empuxo_total_kN if empuxo_total_kN > 0 else np.nan

    return {
        "PARÂMETROS OPERACIONAIS": {
            "Mach de voo": dados["M"],
            "Velocidade de voo [m/s]": u,
            "Rotação N2": N2,
        },

        "VAZÕES MÁSSICAS": {
            "Vazão de ar [kg/s]": m_ar,
            "Vazão de combustível [kg/s]": m_f,
            "Razão combustível/ar": f,
            "Vazão na turbina [kg/s]": m_total,
        },

        "ESTADOS TERMODINÂMICOS": {
            "Temperatura T02 [K]": T02,
            "Pressão P02 [kPa]": P02,
            "Temperatura T03 [K]": T03,
            "Pressão P03 [kPa]": P03,
            "Temperatura T04 [K]": T04,
            "Pressão P04 [kPa]": P04,
            "Temperatura T05 [K]": T05,
            "Pressão P05 [kPa]": P05,
            "Temperatura T06s [K]": T06s,
            "Temperatura T06 [K]": T06,
            "Pressão P06 [kPa]": P06,
        },

        "TURBINA LIVRE": {
            "Trabalho isentrópico [kJ/kg]": W_tl_s,
            "Trabalho real [kJ/kg]": W_tl,
            "Potência da turbina [kW]": POT_tl,
            "Potência da turbina [hp]": POT_tl * 1.34102,
        },

        "BOCAL": {
            "Velocidade de saída do bocal [m/s]": u_s,
            "Empuxo Específico do bocal [m/s]": empuxo_especifico_bocal_ms,
            "Empuxo Específico do bocal [kN.s/kg]": empuxo_especifico_bocal_kNs_kg,
            "Empuxo do bocal [kN]": empuxo_bocal_kN,
        },

        "HÉLICE E CAIXA": {
            "Potência na saída da caixa de redução [kW]": POT_eixo,
            "Potência útil na hélice [kW]": POT_util,
            "Empuxo da hélice [kN]": empuxo_helice_kN,
            "Empuxo total [kN]": empuxo_total_kN,
        },

        "CONSUMO": {
            "Consumo de combustível [kg/s]": m_f,
            "Consumo esp. no eixo BSFC [kg/(kW.s)]": BSFC,
            "Consumo esp. equivalente EBSFC [kg/(kW.s)]": EBSFC,
            "TSFC [kg/(kN.s)]": TSFC,
        },
    }

# BLOCO 4 - ESCOLHA DO MOTOR A SER SIMULADO

# Escolha do dicionário a ser utilizado, útil pra validação
# NÃO DELETAR O.COPY()
dados_atuais = dados_ex22.copy()

# Interação com o usuário
print("=== SIMULADOR DE MOTORES AERONÁUTICOS ===")
print("1. Turbojato")
print("2. Turbofan")
print("3. Ramjet")
print("4. Turbo-hélice")
opcao = input("Escolha o motor que deseja simular (1-4): ")

modo = input("Deseja simular FORA do ponto de projeto? (S/N): ")
fora_proj = True if modo.upper() == 'S' else False

N2_val = 1.0

if fora_proj:
    N2_val = float(input("Digite o valor da rotação normalizada N2 (Ex: 0.85): "))

if opcao == '1':
    resultado = simular_turbojato(dados_atuais, fora_proj, N2_val)
elif opcao == '2':
    resultado = simular_turbofan(dados_atuais, fora_proj, N2_val)
elif opcao == '3':
    resultado = simular_ramjet(dados_atuais, fora_proj, N2_val)
elif opcao == '4':
    dados_atuais = dados_ex72.copy()
    resultado = simular_turbohelice(dados_atuais, fora_proj, N2_val)

else:
    print("Opção inválida!")
    resultado = None

# Printar resultados de forma formatada
if resultado:
    print("\n" + "="*45)
    print("      RESULTADOS DA SIMULAÇÃO")
    print("="*45)

    for secao, dados_da_secao in resultado.items():
        print(f"\n{secao}")
        print("-" * 30)

        for chave, valor in dados_da_secao.items():

            # Condição para formatar: 3 casas decimais para Temp, Pressão, Vazão e Velocidade
            if "Temp" in chave or "Pressão" in chave or "Vazão" in chave or "Velocidade" in chave:
                print(f"  {chave}: {valor:.3f}")

            # Condição para o resto (Empuxo, TSFC, f): 5 casas decimais
            else:
                print(f"  {chave}: {valor:.5f}")

    print("\n" + "="*45)